### ISSUE TITLE
Suggestion: Limit the movement of the button

### ISSUE THREAD

**Issue by patdel0** [Alinoker/emo-birthday#4]
At the moment, there are times when the button leaves the screen, forcing the user to scroll to see it again. 
Perhaps there's a way where we can limit the button, to not move beyond the user's viewport?

**Comment by Alinoker** [comment]
removed `transform`
from
```
        .image-caption{
transform: translateY(-50%)
```
changed `absolute` for `fixed`
```
        #nobutton {
            position: fixed
```
