### ISSUE TITLE
Suggestion: Add animation to the button's movement

### ISSUE THREAD

**Issue by patdel0** [Alinoker/emo-birthday#5]
Give `transition` a go!

https://github.com/Alinoker/emo-birthday/assets/53922624/84a5807d-9b8b-43e7-85b8-3be65a696036

**Comment by Alinoker** [comment]
at CSS `#nobutton `I have used:
`  transition: left 0.2s cubic-bezier(0.25, 0.1, 0.25, 1), top 1s cubic-bezier(0.25, 0.1, 0.25, 1);  
`
Transition effects define how the button's left and top properties will change over time when they are modified, creating smooth animation effects. 
The left transition is faster (0.2 seconds) while the top transition is slower (1 second), resulting in a combination of speeds for different movement directions
